"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class low_state_t(object):

    __slots__ = ["timestamp", "q", "dq", "ddq", "tau_est", "temperature", "error", "quaternion", "gyroscope", "accelerometer", "rpy"]

    __typenames__ = ["int64_t", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, [18], [18], [18], [18], [18], [18], [4], [3], [3], [3]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.q = [ 0.0 for dim0 in range(18) ]
        """ LCM Type: float[18] """
        self.dq = [ 0.0 for dim0 in range(18) ]
        """ LCM Type: float[18] """
        self.ddq = [ 0.0 for dim0 in range(18) ]
        """ LCM Type: float[18] """
        self.tau_est = [ 0.0 for dim0 in range(18) ]
        """ LCM Type: float[18] """
        self.temperature = [ 0.0 for dim0 in range(18) ]
        """ LCM Type: float[18] """
        self.error = [ 0.0 for dim0 in range(18) ]
        """ LCM Type: float[18] """
        self.quaternion = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.gyroscope = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.accelerometer = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.rpy = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """

    def encode(self):
        buf = BytesIO()
        buf.write(low_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>18f', *self.q[:18]))
        buf.write(struct.pack('>18f', *self.dq[:18]))
        buf.write(struct.pack('>18f', *self.ddq[:18]))
        buf.write(struct.pack('>18f', *self.tau_est[:18]))
        buf.write(struct.pack('>18f', *self.temperature[:18]))
        buf.write(struct.pack('>18f', *self.error[:18]))
        buf.write(struct.pack('>4f', *self.quaternion[:4]))
        buf.write(struct.pack('>3f', *self.gyroscope[:3]))
        buf.write(struct.pack('>3f', *self.accelerometer[:3]))
        buf.write(struct.pack('>3f', *self.rpy[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != low_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return low_state_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = low_state_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.q = struct.unpack('>18f', buf.read(72))
        self.dq = struct.unpack('>18f', buf.read(72))
        self.ddq = struct.unpack('>18f', buf.read(72))
        self.tau_est = struct.unpack('>18f', buf.read(72))
        self.temperature = struct.unpack('>18f', buf.read(72))
        self.error = struct.unpack('>18f', buf.read(72))
        self.quaternion = struct.unpack('>4f', buf.read(16))
        self.gyroscope = struct.unpack('>3f', buf.read(12))
        self.accelerometer = struct.unpack('>3f', buf.read(12))
        self.rpy = struct.unpack('>3f', buf.read(12))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if low_state_t in parents: return 0
        tmphash = (0xe27f0619de01c9b0) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if low_state_t._packed_fingerprint is None:
            low_state_t._packed_fingerprint = struct.pack(">Q", low_state_t._get_hash_recursive([]))
        return low_state_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", low_state_t._get_packed_fingerprint())[0]

