/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "Full_encode.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ArmCommand, ArmCommand, AUTO)


PB_BIND(LegCommand, LegCommand, AUTO)


PB_BIND(LowLevelCmd, LowLevelCmd, 2)


PB_BIND(ArmState, ArmState, AUTO)


PB_BIND(LegState, LegState, AUTO)


PB_BIND(IMUState, IMUState, AUTO)


PB_BIND(LowLevelState, LowLevelState, 2)



